name: Ci branch

on:
  pull_request:
    branches:
      - 'master'

env:
  BASE: ${{ github.ref == 'refs/heads/master' && 'origin/master~1' || 'origin/master' }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn install
      - run: npm install -g nx
      - run: nx affected:lint --base $BASE
      - name: Test
        run: nx affected:test --base $BASE
      - name: Build
        run: nx affected:build --base $BASE
      - name: Docker Build
        if: ${{ github.ref != 'refs/heads/master' }}
        run: nx affected:docker-build --base $BASE
      - name: Docker Push
        if: ${{ github.ref == 'refs/heads/master' }}
        run: nx affected:docker-push --base $BASE
      - name: Deploy
        if: ${{ github.ref == 'refs/heads/master' }}
        run: nx affected:deploy --base $BASE
