name: Ci branch

on:
  pull_request:
    branches:
      - 'master'

env:
  BASE: ${{ github.ref == 'refs/heads/master' && 'master~1' || 'master' }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn install
      - run: npm install -g nx
      - run: nx affected:lint --base $BASE
