name: Ci branch

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

env:
  BASE: ${{ github.ref == 'refs/heads/master' && 'origin/master~3' || 'origin/master~3' }}
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: yarn install
      - run: npm install -g nx
      - run: nx affected:lint --base $BASE
      - name: Test
        run: nx affected:test --base $BASE
      - name: Build
        run: nx affected:build --base $BASE
      - name: Docker Build
        run: nx affected --target docker-build --base $BASE
      - name: Docker Login
        run: nx affected --target docker-login --base $BASE
      - name: Docker Push
        run: nx affected --target docker-push --base $BASE
      - name: Deploy
        run: nx affected --target deploy --base $BASE
      - name: Verify
        run: nx affected --target verify --base $BASE
