name: Ci branch

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

env:
  BASE: ${{ github.ref == 'refs/heads/master' && 'origin/master~1' || 'origin/master' }}
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
  SKYNET_API_KEY: ${{ secrets.SKYNET_API_KEY }}
  PROTOCOL_FRONTEND_SEED: ${{ secrets.PROTOCOL_FRONTEND_SEED }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
          submodules: recursive
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
      - uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.9'
      - run: yarn install
      - run: npm install -g @graphprotocol/graph-cli
      - name: Install poetry
        run: pip install poetry
      - name: Install deps
        run: yarn nx affected --target install --base $BASE
      - name: Check Prettier
        run: yarn check-prettier
      - run: yarn nx affected --target format --base $BASE
      - run: npx nx affected:lint --base $BASE
      - name: Test
        run: npx nx affected:test --base $BASE
      - name: Build
        run: npx nx affected:build --base $BASE

  docker-build:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
      - run: yarn install
      - run: npm install -g @graphprotocol/graph-cli
      - name: Create env file
        run: |
          touch .env
          echo VITE_PROTOCOL_BASE_URL=https://api.govrn.app  >> .env
          echo VITE_PROTOCOL_URL=https://api.govrn.app/graphql  >> .env
          echo VITE_URL=${{secrets.VITE_URL}} >> .env
          echo VITE_INFURA_PROJECT_ID=${{secrets.VITE_INFURA_PROJECT_ID}}  >> .env
          echo VITE_INFURA_PROJECT_SECRET=${{secrets.VITE_INFURA_PROJECT_SECRET}} >> .env
          echo VITE_LINEAR_REDIRECT_URI=https://api.govrn.app/linear/oauth  >> .env
          echo VITE_LINEAR_CLIENT_ID=9131c342273502268438468f08337b29 >> .env
          echo VITE_INFURA_SUBDOMAIN=https://govrn.infura-ipfs.io >> .env
          echo VITE_PUBLIC_ALCHEMY_KEY=${{ secrets.PUBLIC_ALCHEMY_KEY }} >> .env
          echo CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }} >> .env
          echo CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }} >> .env
      - name: Build
        run: npx nx affected:build --configuration production --base $BASE
      - name: Docker Build
        run: npx nx affected --target docker-build --base $BASE --parallel --max-parallel=3
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Login
        run: npx nx affected --target docker-login --base $BASE --parallel --max-parallel=3
      - name: Docker Push
        run: npx nx affected --target docker-push --base $BASE --parallel --max-parallel=3
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm install -g wrangler
      - name: Deploy
        run: npx nx affected --target deploy --base $BASE --parallel --max-parallel=3
      - name: Verify
        run: npx nx affected --target verify --base $BASE --parallel --max-parallel=3
