name: Deploy Api

on:
  push:
    branches:
      - 'master'

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}

jobs:
  # Run code tests before building the image, to ensure it is good to go
  build:
    name: Run code tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        run: |
          run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

      - name: Push to Heroku
        run: docker push registry.heroku.com/govrnairtable-api
