name: Deploy Api

on:
  push:
    branches:
      - 'master'

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}

jobs:
  # Run code tests before building the image, to ensure it is good to go
  build:
    name: Run code tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        run: |
          yarn install
          npx nx build airtable-api
          sudo apt-get install -y heroku

      - name: Push to Heroku
        run: heroku git:remote -a govrnairtable-api
